#!/usr/bin/env ruby

require "DailyProgress"

include DailyProgress

path = ARGV[0]
default_path = "/home/lovepreet/vimwiki/diary/"

DailyProgress.configure(path)
content = DailyProgress.progress
puts content
to_clipboard(content)
