#!/usr/bin/env ruby

require "DailyProgress"

include DailyProgress

path = ARGV[0]
default_path = "C:/Users/LP-Office/vimwiki/diary/"

DailyProgress.configure(path)
content = DailyProgress.progress
puts content
to_clipboard(content)
