#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/daily_progress'
include DailyProgress

path = ARGV[0].nil? ? "#{Dir.home}/vimwiki/diary/" : ARGV[0].nil?
puts "Configured path: #{path}"
DailyProgress.configure(path)
content = DailyProgress.progress
puts content
to_clipboard(content)
